<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header" style="color: white;">
            <h3> <?php if (isset($this->title)) echo $this->title; ?></h3>
        </div>
    </div>
</nav>

<div>
    <?php if ($this->message) echo $this->message; ?>
    <p>&nbsp;</p>
    <a href="<?php echo BASE_URL; ?>" style="text-decoration: none;"> Go to Home Page </a> | 
    <a href="javascript:history.back(1)" style="text-decoration: none;"> Go to Back </a>

    <?php if (!Session::get('auth')): ?>
        | <a href="<?php echo BASE_URL . 'log/in'; ?>" style="text-decoration: none;"> Login </a> 
    <?php endif; ?>
</div>
