<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="header"> 
        <div class="container-fluid">
            <div class="navbar-header" style="color: white;">
                <div class="brand">
                    <h3> <?php if (isset($this->title)) echo $this->title; ?></h3>
                </div>
            </div>
        </div>

    </div>
</nav>

<div style="padding-top: 45px;"></div>

    <?php if ($this->message) echo $this->message; ?>
    <p>&nbsp;</p>
    <a href="<?php echo BASE_URL; ?>" style="text-decoration: none;"> Go to Home Page </a> | 
    <a href="javascript:history.back(1)" style="text-decoration: none;"> Go to Back </a>
